# Loads default set of integrations. Do not remove.
default_config:

# +----------------------------------------------------------------------------+
# | Setting for the dashboard                                                  |
# +----------------------------------------------------------------------------+
lovelace:
  dashboards:

    lovelace-homeplay:
      mode: yaml
      filename: homeplay.yaml
      title: HomePlay
      icon: phu:homekit
      show_in_sidebar: true

    home-os:
      mode: yaml
      filename: HomeOS.yaml
      title: HomeOS
      icon: phu:homekit
      show_in_sidebar: true


# +----------------------------------------------------------------------------+
# | Definition for the theme folder and file                                   |
# +----------------------------------------------------------------------------+
frontend:
  themes:
    light: !include_dir_merge_named themes/HomeOS/light/
    dark: !include_dir_merge_named themes/HomeOS/dark/

# +----------------------------------------------------------------------------+
# | Definition for extra module                                                |
# +----------------------------------------------------------------------------+
  extra_module_url:
    - /local/homeplay_assets/community/custom-brand-icons/custom-brand-icons.js #Add new icon from elax46, use phu:
    - /local/homeplay_assets/community/kiosk-mode/kiosk-mode.js
    - /local/homeplay_assets/fonts.css
    - /local/homeplay_assets/lovelace-card-mod/card-mod.js # Performance improvement called as fronted instead of lovelace resource



# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homekit: !include homekit.yaml


homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config





##############################################
# UI Librairies
##############################################








panel_iframe:
  zigbeebasement:
    title: "Zigbee Basement"
    url: "http://192.168.0.20:8081"
    icon: mdi:zigbee
##############################################
# Group
##############################################

group:
  persons:
    name: family
    entities:
      - person.sebastien_logeais
      - person.lynn

  hass_update_notification:
    name: Home assistant Update
    entities:
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update

  router_update_notification:
    name: Velop Mesh Wifi Notification
    entities:
      - update.bureau_update
      - update.salon_update
      - update.sous_sol_update

  all_light:
    name: All light (switch and Light)
    entities:
      - light.dimmerlivingroom
      - light.dreamview_t1
      - light.floodlight_kitchen
      - light.grouplightkitchencounter
      - light.groupspotlightkitchen
      - light.groupspotlightkitchensink
      - light.kitchen_leds
      - light.lampe_salle_de_bain
      - light.stairs_lights
      - light.ambientlightbedroomclara_lightbulb
      - light.wiz_rgbw_tunable_6261a4
      - switch.switch_basement
      - switch.switchexterieurback_switch
      - switch.switchexteriorfront
      - switch.smartplugclara
      - switch.switchvestibule_switch




##############################################
# BINARY SENSOR
##############################################

binary_sensor:
  - platform: tod
    name: 7-9AM
    after: "7:00"
    before: "9:00"

sensor:
  - platform: seventeentrack
    username: !secret seventeentrack_username
    password: !secret seventeentrack_password

  # Documentation
  # https://developpeurs.stm.info/documentation/gtfsrtv2
  # https://github.com/zacs/ha-gtfs-rt/issues/22

  - platform: gtfs_rt
    trip_update_url: "https://api.stm.info/pub/od/gtfs-rt/ic/v2/tripUpdates"
    vehicle_position_url: "https://api.stm.info/pub/od/gtfs-rt/ic/v2/vehiclePositions"
    apikey: !secret gtfs_rt_apikey
    departures:
      - name: "191 Bus Est"
        route: 191
        stopid: 57237
      - name: "491 Express Est"
        route: 491
        stopid: 57244

  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "time_date"

  - platform: sun2
    monitored_conditions:
      - sun_phase

  ##########
  # FILTER #
  ##########
  - platform: filter
    name: "Filter_feel_like_temperature"
    entity_id: sensor.montreal_wind_chill
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 5
        precision: 2

  # Determine the min and max humidity in the house
  - platform: min_max
    name: humidity_min
    type: min
    entity_ids:
      - sensor.temperaturesensor_masterbedroom_humidity
      - sensor.temperaturesensor_basement_humidity
      - sensor.temperaturesensor_clara_humidity

  - platform: min_max
    name: humidity_max
    type: max
    entity_ids:
      - sensor.temperaturesensor_masterbedroom_humidity
      - sensor.temperaturesensor_basement_humidity
      - sensor.temperaturesensor_clara_humidity

  #######################################################################################
  ## Templates (Used for updating text in the UI and converting sensors to CSS values )
  #######################################################################################

  - platform: template

    sensors:
      ##################################################################################
      ### TOP BAR TEMPLATE #############################################################
      ##################################################################################

      climate_temp:
        value_template: "{{ state_attr('climate.entryway','current_temperature') | round(0)}}°"

      climate_text:
        value_template: >
          {% if is_state_attr('climate.entryway', 'hvac_action', 'heating') %}
            Chauffe à {{ state_attr('climate.entryway','target_temp_low') | round(1) }}°
          {% elif is_state_attr('climate.entryway', 'hvac_action', 'cooling') %}
            Refroidi à {{ state_attr('climate.entryway','target_temp_high') | round(1) }}°
          {% else %}
            {{ state_attr('climate.entryway','target_temp_low') | round(1) }} - {{ state_attr('climate.entryway','target_temp_high') | round(1) }}°
          {% endif %}

      humidity_min_max:
        value_template: "{{ states('sensor.humidity_min') | round(0) }} - {{ states('sensor.humidity_max') | round(0) }} %"

      ## Find the Min and max temperature in the house
      ## Do not forget to add new temperature sensor to these math
      temperature_min:
        value_template: >
          {{ [
              states('sensor.entryway_temperature'),
              states('sensor.temperaturesensor_basement_temperature'),
              states('sensor.temperaturesensor_clara_temperature'),
              states('sensor.temperaturesensor_masterbedroom_temperature')
              ] | min 
          }}

      temperature_max:
        value_template: >
          {{ [
              states('sensor.entryway_temperature'),
              states('sensor.temperaturesensor_basement_temperature'),
              states('sensor.temperaturesensor_clara_temperature'),
              states('sensor.temperaturesensor_masterbedroom_temperature')
              ] | max 
          }}
      temperature_min_max:
        value_template: "{{ states('sensor.temperature_min') | round(1) }} - {{ states('sensor.temperature_max') | round(1) }}°"

      lights_on_count:
        friendly_name: "Lights on count"
        value_template: "{{ expand('group.all_light') | selectattr('state','eq','on') | list | count }} lumières allumées"

      battery_min_max:
        value_template: >
          {{ states.sensor 
            | selectattr('attributes.device_class', 'defined') 
            | selectattr('attributes.device_class', 'eq', 'battery') 
            | map(attribute='state') 
            | map('int', 0)
            | list | min 
          }} - 
          {{ states.sensor 
            | selectattr('attributes.device_class', 'defined') 
            | selectattr('attributes.device_class', 'eq', 'battery') 
            | map(attribute='state') 
            | map('int', -1)
            | list | max 
          }}%

      ##################################################################################
      ### TASKBAR TEMPLATE #############################################################
      ##################################################################################

      ## Converts time and date into sentence for UI
      day:
        value_template: >
          {{["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"][now().weekday()]}}

      month:
        value_template: >
          {% set months = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"] %}
          {{ strptime(states('sensor.date'), '%Y-%m-%d').day }}
          {{ months[now().month-1] }}
      date_string:
        friendly_name: "Full Date"
        value_template: "{{ states('sensor.day') }} {{ states('sensor.month') }}"


      ##################################################################################
      ### WEATHER CARD TEMPLATE ########################################################
      ##################################################################################

      ### feel like temperature
      # Based on template sensor from https://www.home-assistant.io/integrations/environment_canada/
      feel_like:
        value_template: >
          {% if not is_state('sensor.montreal_humidex', 'unknown') %}
            {{ states('sensor.montreal_humidex') | round(0) }}°
          {% elif not is_state('sensor.montreal_wind_chill', 'unknown') %}
            {{ states('sensor.montreal_wind_chill') | round(0) }}°
          {% else %}
            {{ states('sensor.montreal_temperature') | round(0) }}°
          {% endif %}

      ### High and low temperature
      high_low_temp:
        value_template: >
          ↑ {{ states('sensor.montreal_high_temperature') }}° ↓ {{ states('sensor.montreal_low_temperature') }}°

      ### Warning template
      weather_warning:
        value_template: >
          {% if is_state('sensor.montreal_warnings', '0') %}
            off
          {% else %}
            on
          {% endif %}
      weather_warning_statement_1:
        value_template: >
          {{ state_attr('sensor.montreal_warnings','alert_1')|capitalize }}

      weather_bg_condition2:
        value_template: >
          {% if is_state('input_select.hass_theme_selected','light') %}
            {{ states('sensor.montreal_icon_code') | round(0) }}
          {% elif is_state('input_select.hass_theme_selected','dark') %}
            {{ states('sensor.montreal_icon_code') | round(0) + 100  }}
          {% endif %}

      ##################################################################################
      ### OTHERS TEMPLATE ##############################################################
      ##################################################################################

      humidity_masterbedroom:
        value_template: >
          {{ states('sensor.temperaturesensor_masterbedroom_humidity') | round(0) }}%
      temperature_delta: # if delta temp more than a certain value start fan to balance temperature
        value_template: >
          {{ '%.3f' | format (states('sensor.temperature_max') | float - 
                      states('sensor.temperature_min') | float) }}

      climate_hvac_action:
        value_template: >
          {{state_attr('climate.entryway','hvac_action')}}
      climate_fan_mode:
        value_template: >
          {{state_attr('climate.entryway','fan_mode')}}

      garbage_weekday:
        value_template: >
          {{as_timestamp(states.schedule.garbage.attributes.next_event) | timestamp_custom('%A',false) }}

      recycling_weekday:
        value_template: >
          {{as_timestamp(states.schedule.recycling.attributes.next_event) | timestamp_custom('%A',false) }}
################################################################################
### SEPARATED SWITCH FOR CLIMATE ###############################################
################################################################################

switch:
  - platform: template
    switches:
      climate_fan:
        friendly_name: "Ventilateur"
        value_template: "{{ is_state_attr('climate.entryway', 'fan_mode', 'on') }}"
        turn_on:
          service: climate.set_fan_mode
          data:
            entity_id: climate.entryway
            fan_mode: "on"
        turn_off:
          service: climate.set_fan_mode
          data:
            entity_id: climate.entryway
            fan_mode: "off"

      climate_eco_mode:
        friendly_name: "Eco Mode"
        value_template: "{{ is_state_attr('climate.entryway', 'preset_mode', 'eco') }}"
        turn_on:
          service: climate.set_preset_mode
          data:
            entity_id: climate.entryway
            preset_mode: "eco"
        turn_off:
          service: climate.set_preset_mode
          data:
            entity_id: climate.entryway
            preset_mode: "none"

################################################################################
### GARBAGE ####################################################################
################################################################################


