#..............................................................................
#.HHHH...HHHH.........................................OOOOOOO......SSSSSSS.....
#.HHHH...HHHH........................................OOOOOOOOOO...OSSSSSSSS....
#.HHHH...HHHH.......................................eOOOOOOOOOOO..OSSSSSSSSS...
#.HHHH...HHHH....oooooo..ommmmmmmmmmmmm....eeeeee...eOOOO..OOOOO.OOSSS..SSSS...
#.HHHH...HHHH..ooooooooo.ommmmmmmmmmmmmm..eeeeeeee.eeOOO....OOOOOOOSSS.........
#.HHHHHHHHHHH..oooo.oooooommmm.mmmmmmmmm.meee.eeee.eeOO......OOOO.OSSSSSS......
#.HHHHHHHHHHH.Hooo...ooooommm..mmmm..mmmmmeee..eeeeeeOO......OOOO..SSSSSSSSS...
#.HHHHHHHHHHH.Hooo...ooooommm..mmmm..mmmmmeeeeeeeeeeeOO......OOOO....SSSSSSS...
#.HHHH...HHHH.Hooo...ooooommm..mmmm..mmmmmeeeeeeeeeeeOOO....OOOOO.......SSSSS..
#.HHHH...HHHH.Hooo...ooooommm..mmmm..mmmmmeee.......eOOOO..OOOOO.OOSS....SSSS..
#.HHHH...HHHH..oooo.oooooommm..mmmm..mmmmmeee..eeee.eOOOOOOOOOOO.OOSSSSSSSSSS..
#.HHHH...HHHH..ooooooooo.ommm..mmmm..mmmm.eeeeeeee...OOOOOOOOOO...OSSSSSSSSS...
#.HHHH...HHHH....oooooo..ommm..mmmm..mmmm..eeeeee......OOOOOO......SSSSSSSS....
#..............................................................................

# +----------------------------------------------------------------------------+
# | Description:                                                               |
# | This is the main file for the HomeOS dashboard                             |
# +----------------------------------------------------------------------------+
# | Author: Sebastien Logeais                                                  |
# +----------------------------------------------------------------------------+
# | Date: 25 Aug 2023                                                          |
# +----------------------------------------------------------------------------+

kiosk_mode:
  hide_header: true

# all relevant template will be find
button_card_templates: !include_dir_merge_named HomeOS_Module/

views:
  - type: custom:grid-layout
    title: HomeOS
    background: var(--background)
    layout:
      height: 61.8vw # 16/10 screen
      margin: 0 0.8vw 0.8vw 0 # top right bottom left
      grid-template-columns: 0.5fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr
      grid-template-rows: 0.25fr 1fr 1fr 1fr 1fr 1fr
      grid-gap: 0.8vw
      display: grid
      justify-content: stretch
      align-content: stretch
      justify-items: stretch
      align-items: stretch
      grid-template-areas: |
        "apps topbar topbar topbar topbar topbar topbar topbar"
        "apps weather weather map map map map pack"
        "apps weather weather map map map map pack"
        "apps weather weather map map map map 3"
        "apps calendar calendar map map map map 4"
        "apps calendar calendar . . . . 5"
  
    
    cards:
# +----------------------------------------------------------------------------+
# | Weather Area Definition                                                    |
# +----------------------------------------------------------------------------+
      - type: custom:mod-card 
        view_layout:
          grid-area: weather
        # the following style ensure the card resize to the grid
        style: |
          ha-card {
            display: contents;   
          }
        card: !include HomeOS_Module/weather/weather_card.yaml

  
# +----------------------------------------------------------------------------+
# | Calendar Area Definition                                                   |
# +----------------------------------------------------------------------------+
      - type: custom:mod-card
        view_layout:
          grid-area: calendar
        style: |
          ha-card {
            display: contents;   
          }
        card: !include HomeOS_Module/Calendar/calendar_card.yaml

      
# +----------------------------------------------------------------------------+
# | Map Area Definition                                                        |
# +----------------------------------------------------------------------------+
      - type: custom:mod-card
        view_layout:
          grid-area: map
        style: |
          ha-card {
            display: contents;   
          }
        card: !include HomeOS_Module/map/map_card.yaml
    
# # +----------------------------------------------------------------------------+
# # | seventeen track Package Tracking Definition                                |
# # +----------------------------------------------------------------------------+
#       - type: custom:mod-card
#         view_layout:
#           grid-area: pack
#         style: |
#           ha-card {
#             display: contents;   
#           }
#         card: !include HomeOS_Module/seventeen_track/seventeen_track_card.yaml